### ISSUE TITLE
Underscores theme submodule ref missing

### ISSUE THREAD

**Issue by pdewouters** [humanmade/hm-base#21]
The `.gitmodules` entry for `_s` was removed but there are still refs hanging around so if you do `git submodule update --init --recursive` it will throw an error.

Either the submodule should be cleanly removed or add this back

```
[submodule "content/themes/_s"]
	path = content/themes/_s
	url = git@github.com:Automattic/_s.git
```

**Comment by pdewouters** [comment]
@mattheu let me know, and I'll do a PR to fix

**Comment by mattheu** [comment]
Looks like it was removed here with no real explanation: https://github.com/humanmade/hm-base/commit/3f111c8b77f1a378254a36fcf12f57449efabd0e

Personally - I'd say we remove and don't include a submodule. I'm not sure you would ever want an underscores submodule even if you were going to use it as the base for your theme.

**Comment by joehoyle** [comment]
I think we should remove it. I had intended to, but obviously messed that up. I'd rather hm-base be a base repo that you add stuff to, because realistically `_s` isn't used in every project we do, and most people just don't bother to remove it.

**Comment by mattheu** [comment]
I think the only reason to keep it as a submodule is if you were to base a child theme off it - which I think you would never do.

**Comment by pdewouters** [comment]
Closing as it was removed
