### ISSUE TITLE
Setting up local config file

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-base#30]
In the readme, the setup instructions say use `mv wp-config-sample.php wp-config-local.php` to create a local config file. 

Two things:
- The file `wp-config-sample.php` doesn't exist. It is `wp-config-local-sample.php`
- Using `mv` renames the file, which removes the sample file from the project. Should we use `cp` instead so the sample is still in the repo?

**Comment by mikeselander** [comment]
Looks like this was addressed via 9f1fef5757bfbecfccb26aafaef077a0fdfb6b7a
