### ISSUE TITLE
Grunt is not configured

### ISSUE THREAD

**Issue by sambulance** [humanmade/hm-base#61]
The theme structure and [instructions in the functions file](https://github.com/humanmade/hm-base/blob/master/content/themes/hm-base-theme/functions.php#L62) suggest Grunt should be used with the theme, but there are no config files included. Should these go in the project root?

**Comment by mikeselander** [comment]
Since we're using Webpack for Gutenberg blocks and for React builds, should we instead remove all reference to Grunt and replace that with Webpack as the standardized tool for builds?

cc @rmccue and @kadamwhite

**Comment by kadamwhite** [comment]
+1. Grunt doesn’t have a strong place in our current rolling ecosystem. In my opinion, Anything relating to sequencing tasks should be done with a bash or node script, and executed via npm scripts; and anything relating to actually building or transforming assets should be accomplished through a tool like Webpack.

**Comment by rmccue** [comment]
I agree, we're moving away from generic task runners like Grunt and Gulp in favour of specialised, best-in-class tooling. However, I don't know if we're there *yet*; we still have a lot of sites with e.g. just SCSS and some jQuery stuff.

@sambulance @mattheu Interested to know your thoughts on this.

**Comment by sambulance** [comment]
>  we still have a lot of sites with e.g. just SCSS and some jQuery stuff

Are these new or existing builds? Existing ones wouldn't need to migrate, would they?

I suggested in #72 that we could have a range of starting points based on requirements, however I think it might be best to have consistency with build tooling, so people can easily move between projects and understand how things work.

**Comment by mattheu** [comment]
I think the question is around what should we include in our boilerplate `hm-base`. I personally think we should limit this to things every site uses - I hate installing boilerplate and then going through and deleting half of it.

> we still have a lot of sites with e.g. just SCSS and some jQuery stuff.

For sites like this, you can mostly get away with a few node scripts. There may be sites that benefit from something like gulp - but they can just be configured on a per-site basis rather than including this stuff in hm-base.

That does leave a question around webpack. Is webpack overkill if our JS is really minimal? Should we bother writing ES6 and transpiling on new projects or should we be encouraging this regardless?

**Comment by kadamwhite** [comment]
I don't consider Webpack overkill for minimal JS. I think the benefits of consistency across projects, modern library usage / better build performance, and ability for all of us to experiment equally with modern JS syntax are more than worth a few extra hours of setup time wrapping our heads around the webpack build. And if we do our job right on hm-base and in the handbook, we should have a pretty drop-in webpack config we can use even on those projects :)

**Comment by mikeselander** [comment]
It seems like we have a consensus to switch to WebPack instead of Grunt. I've opened #86 to track a standardized WebPack build.

**Comment by sambulance** [comment]
We should probably still remove the grunt references.

**Comment by kadamwhite** [comment]
Reopening to track removing the grunt references

**Comment by mikeselander** [comment]
Yup, good call @sambulance - thanks you for catching that!
