### ISSUE TITLE
Ensure robots.txt discourages all on dev/staging servers

### ISSUE THREAD

**Issue by joemcgill** [humanmade/hm-base#62]
It's easy to forget to change the "discourage Google" setting in WP > Settings > Reading each time you add a site to one of the environments on the server, which can lead to our development sites getting crawled. To avoid this, we could add code to our project configs that forces this setting on our dev/staging environments.

**Comment by mikeselander** [comment]
I think that this might have been addressed within our stack? @joehoyle or @nathanielks do you know?

**Comment by nathanielks** [comment]
We don't have a robots.txt, but we _do_ disable indexing via WordPress in non-production environments: https://github.com/humanmade/hm-platform/blob/master/load.php#L59-L67

**Comment by mikeselander** [comment]
Do you think the above would satisfy the need @joemcgill?

**Comment by joemcgill** [comment]
Missed responding to this earlier. I agree that this should do the trick. We should add documentation for `HM_DISABLE_INDEXING` to [the platform/deploys page on the engineering handbook](https://engineering.hmn.md/platform/deploys/).
